### ISSUE TITLE
window下也需要自己编译安装 sqlcipher 才能解密吗？

### ISSUE THREAD

**Issue by lujihong** [lw396/ChatCopilot#1]

**Comment by lw396** [comment]
暂时没有兼容window系统

**Comment by lujihong** [comment]
我看你用了这个包 github.com/mutecomm/go-sqlcipher 不是已经内嵌了sqlcipher了吗，为啥在mac下还要单独brew install sqlcipher，我已经在window上实现了解密，也是用的这个包，没有单独编译安装sqlcipher。

**Comment by lw396** [comment]
> 我看你用了这个包 github.com/mutecomm/go-sqlcipher 不是已经内嵌了sqlcipher了吗，为啥在mac下还要单独brew install sqlcipher，我已经在window上实现了解密，也是用的这个包，没有单独编译安装sqlcipher。
是我疏忽了，我卸载sqlcipher后还是可以执行的。

**Comment by lujihong** [comment]
brew install sqlite 你测试没，是不是也可以不用安装？

**Comment by lw396** [comment]
测试过了，卸载 sqlcipher 后也是可以读取到数据的

**Comment by lw396** [comment]
> > 测试过了，卸载 sqlcipher 后也是可以读取到数据的
> > 我说的是sqlite卸载后可以吗？因为我在windows下没有单独安装sqlite

也是可以的

**Comment by lujihong** [comment]
好的
